### ISSUE TITLE
Vite 5 / Rollup 4 build warning in v2.6.0

### ISSUE THREAD

**Issue by Kamahl19** [pmndrs/jotai#2269]
The combination of upgrading to Vite 5 (Rollup 4) and Jotai 2.6.0 results in an error during building
```
node_modules/jotai/esm/react.mjs (1:0) Error when using sourcemap for reporting an error: Can't resolve original location of error.
```

This error does not happen in 2.5.1 and also does not happen in Vite 4 + Jotai 2.6.0.

**Comment by dai-shi** [comment]
@himself65 Was `rollup-plugin-banner2` too easy solution??

**Comment by himself65** [comment]
> @himself65 Was `rollup-plugin-banner2` too easy solution??

Might be. I was worried about this before 
https://github.com/pmndrs/jotai/discussions/2241#discussioncomment-7514559

**Comment by himself65** [comment]
Here is the minimum reproduction

https://stackblitz.com/edit/vitejs-vite-v2qh9v?file=src%2Fmain.ts

**Comment by himself65** [comment]
@Kamahl19 Hi, would you try to use https://github.com/huozhi/rollup-plugin-swc-preserve-directives to see if the error disappear

**Comment by himself65** [comment]
> I get even more errors. Maybe I misunderstood. Should I just add it to the vite plugin?

Could you please share you vite config?

**Comment by himself65** [comment]
I just tried, and there's only one warning that won't cause building interrupt.

```
main.js → output...
(!) Module level directives cause errors when bundled, "use client" in "node_modules/.pnpm/jotai@2.6.0_react@18.2.0/node_modules/jotai/esm/react.mjs" was ignored.
node_modules/.pnpm/jotai@2.6.0_react@18.2.0/node_modules/jotai/esm/react.mjs (1:0)
1: 'use client';
   ^
2: import ReactExports, { createContext, useContext, useRef, createElement, useReducer, useEffect, useDebugValue, useCal...
3: import { getDefaultStore, createStore } from 'jotai/vanilla';
```

**Comment by himself65** [comment]
Anyway, I'm working on a new implementation that won't cause this error

**Comment by himself65** [comment]
I've published npm `jotai-test-react-server` with a patch version; could you please try that again?

**Comment by dai-shi** [comment]
Can this be an upstream issue?

https://github.com/vitejs/vite/issues/15012

**Comment by dai-shi** [comment]
Any updates on this? Anyone?

**Comment by himself65** [comment]
https://stackblitz.com/edit/vitejs-vite-v2qh9v

```shell
❯ npm run build

> vite-typescript-starter@0.0.0 build
> tsc && vite build

vite v5.1.4 building for production...
node_modules/jotai/esm/react.mjs (1:0) Module level directives cause errors when bundled, "use client" in "node_modules/jotai/esm/react.mjs" was ignored.
✓ 7 modules transformed.
x Build failed in 377ms
error during build:
RollupError: "createContext" is not exported by "__vite-optional-peer-dep:react:jotai", imported by "node_modules/jotai/esm/react.mjs".
file: /home/projects/vitejs-vite-v2qh9v/node_modules/jotai/esm/react.mjs:3:23
1: 'use client';
2: import ReactExports, { createContext, useContext, useRef, createElement, useReducer, useEffect, useDebugValue, useCal...
3: import { getDefaultStore, createStore } from 'jotai/vanilla';
                          ^
4: 
5: const StoreContext = createContext(void 0);
    at Module.error (/home/projects/vitejs-vite-v2qh9v/node_modules/rollup/dist/es/shared/parseAst.js:469:30)
    at Module.error (/home/projects/vitejs-vite-v2qh9v/node_modules/rollup/dist/es/shared/node-entry.js:12762:29)
    at Module.traceVariable (/home/projects/vitejs-vite-v2qh9v/node_modules/rollup/dist/es/shared/node-entry.js:13199:29)
    at ModuleScope.findVariable (/home/projects/vitejs-vite-v2qh9v/node_modules/rollup/dist/es/shared/node-entry.js:11616:39)
    at Identifier.bind (/home/projects/vitejs-vite-v2qh9v/node_modules/rollup/dist/es/shared/node-entry.js:7204:40)
    at CallExpression.bind (/home/projects/vitejs-vite-v2qh9v/node_modules/rollup/dist/es/shared/node-entry.js:4650:23)
    at CallExpression.bind (/home/projects/vitejs-vite-v2qh9v/node_modules/rollup/dist/es/shared/node-entry.js:8837:15)
    at VariableDeclarator.bind (/home/projects/vitejs-vite-v2qh9v/node_modules/rollup/dist/es/shared/node-entry.js:4650:23)
    at VariableDeclaration.bind (/home/projects/vitejs-vite-v2qh9v/node_modules/rollup/dist/es/shared/node-entry.js:4646:28)
    at Program.bind (/home/projects/vitejs-vite-v2qh9v/node_modules/rollup/dist/es/shared/node-entry.js:4646:28)

```

**Comment by himself65** [comment]
Related https://github.com/vitejs/vite/issues/15012#issuecomment-1825035992

**Comment by dai-shi** [comment]
thanks. btw, it's not "error" that stops building, but just "warning", correct?

**Comment by himself65** [comment]
oh yeah, an warning

**Comment by drush** [comment]
This plugin to remove all the 'use client' refs may do the trick https://stackoverflow.com/questions/78744180/vite-react-use-client-sourcemap-warning

**Comment by dai-shi** [comment]
Let's close this as https://github.com/vitejs/vite/issues/15012 is closed.

Please open a new discussion for follow-up questions if any.
