### ISSUE TITLE
[Bug] atom state not found in flush, undefined @ jotai 1.4.0

### ISSUE THREAD

**Issue by AndrejJurkin** [pmndrs/jotai#789]
Hi, I am currently using jotai version 1.4.0 in ReactNative. My console is spamming the following warning:
```
[Bug] atom state not found in flush, undefined
at node_modules\react-native\Libraries\LogBox\LogBox.js:117:10 in registerWarning
at node_modules\react-native\Libraries\LogBox\LogBox.js:63:8 in warnImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:36:4 in console.warn
at node_modules\expo\build\environment\react-native-logs.fx.js:18:4 in warn
at node_modules\jotai\index.js:500:17 in unmountAtom
at [native code]:null in forEach
at node_modules\jotai\index.js:490:3 in mountAtom
at http://192.168.88.253:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:251806:20 in <unknown>
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15561:31 in commitHookEffectListMount
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:15618:35 in commitPassiveHookEffects
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:265:4 in invokeGuardedCallbackImpl
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:476:2 in invokeGuardedCallback
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18795:29 in flushPassiveEffectsImpl
at node_modules\scheduler\cjs\scheduler.development.js:653:23 in unstable_runWithPriority
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18647:29 in scheduleCallback$argument_1
at node_modules\scheduler\cjs\scheduler.development.js:597:41 in workLoop
at node_modules\scheduler\cjs\scheduler.development.js:552:23 in flushWork
at node_modules\scheduler\cjs\scheduler.development.js:42:17 in _flushCallback
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:383:16 in callTimers
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:416:4 in __callFunction
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:109:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:4 in callFunctionReturnFlushedQueue
at [native code]:null in callFunctionReturnFlushedQueue
```
I've seen some older post which was dealing with the same issue on version 0.16.11, and apparently it was fixed since then. 

Can anybody suggest what could be the reason for that, please?

**Comment by dai-shi** [comment]
> [Bug] atom state not found in flush

This log is removed in v1.3.6. https://github.com/pmndrs/jotai/commit/b98f865b9f1342dcf61f88cb282fa3994b827449#diff-e8b16c5dbf90acb3df9a72c2ad370d1d8223b094ee3d50b6277b74894ae8c580L584
Can you make sure which version you are using?

**Comment by dai-shi** [comment]
I'm not sure what's happening. Would you be able to create a small reproduction with expo snack?
